name : Terraform deploy
on :
  push :
    branches :
      - main
  workflow_dispatch :
      inputs:
          action:
              description: 'Action to perform'
              required: true
              default: 'apply'
              type: choice
              options:
                - apply
                - destroy
env:
    AWS_REGION: ap-south-1
    TF_VERSION: 1.6.0

jobs :
  terraform :
    name : Run Terraform
    runs-on : ubuntu-latest

    steps :
      - name : Checkout Code
        uses : actions/checkout@v4

      - name : Configure AWS
        uses : aws-actions/configure-aws-credentials@v4
        with :
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region : ${{ env.AWS_REGION }}

      - name : Setup Terraform
        uses : hashicorp/setup-terraform@v3
        with :
          terraform-version : ${{ env.TF_VERSION }}

      - name : Terraform init stage
        run : terraform init

      - name : Terraform plan stage
        run : terraform plan

      - name : Terraform apply stage
        if : github.event_name == 'push' || github.event.inputs.action == 'apply'
        run : terraform apply -auto-approve

      - name : Terraform destroy stage
        if : github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run : terraform destroy -auto-approve